source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AlamofireRealmObjectMapperExample' do
  pod 'AlamofireRealmObjectMapper', :path => '../'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'RealmSwift'
  pod 'SwiftFetchedResultsController'
end
